version: '3'
services:
                gitlab:
                        image: gitlab/gitlab-ce:latest
                        hostname: test.huliyuan.com
                        container_name: gitlab
                        restart: always
                        ports:
                         - "80:80"
                         - "443:443"
                         - "8022:22"
                        volumes:
                         - "/data/gitlab/config:/etc/gitlab"
                         - "/data/gitlab/logs:/var/log/gitlab"
                         - "/data/gitlab/data:/var/opt/gitlab"
                        network_mode: "bridge"
                        

